name: fenix_case
description: "TMDB Movie App - Flutter ile geliştirilmiş film arama ve favori yönetimi uygulaması."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  dartz: ^0.10.1
  dio: ^5.4.1
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  json_annotation: ^4.8.1
  get_it: ^7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
