name: fenix_case
description: "A new Flutter project for Fenix Case Study"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  dio: ^5.8.0+1
  cached_network_image: ^3.4.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
