name: flutter_base_project
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+2

environment:
  flutter: 3.13.6
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core
  intl: any
  collection: any
  shared_preferences: ^2.1.1
  background_json_parser: ^1.0.4 # Json parse işlemini yapar

  # Network
  http: ^0.13.5
  cached_network_image: ^3.2.3
  connectivity: ^3.0.6

  # UI
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.6
  overlay_kit: ^1.0.8

  # State manager
  get: ^4.6.5

  # Error handler
  dop_logger:
    git:
      url: https://github.com/dophub/applogger.git
      ref: prod-0801

dev_dependencies:
  # test_coverage: ^0.5.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: any
  dart_code_metrics: ^5.5.1
  build_runner:
  flutter_gen_runner:


flutter_gen:
  output: lib/app/constants/assets
  line_length: 120

  integrations:
    flutter_svg: true
  fonts:
    enabled: false

flutter:
  uses-material-design: true
  assets:
    - assets/visual/icons/
    - assets/visual/images/


  fonts:
    - family: GreycliffCF
      fonts:
        - asset: assets/fonts/GreycliffCF-Light.ttf
          weight: 300
        - asset: assets/fonts/GreycliffCF-Regular.ttf
          weight: 400
        - asset: assets/fonts/GreycliffCF-Medium.ttf
          weight: 500
        - asset: assets/fonts/GreycliffCF-DemiBold.ttf
          weight: 600
        - asset: assets/fonts/GreycliffCF-Bold.ttf
          weight: 700